nodeLinker: node-modules

packageExtensions:
  "@docusaurus/bundler@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-*@*":
    peerDependencies:
      "@mdx-js/react": "*"
      react: "*"
      react-dom: "*"
  "@docusaurus/theme-*@*":
    peerDependencies:
      "@mdx-js/react": "*"
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
